#!/usr/bin/python3
"""test rectangle module"""


import unittest
from models.rectangle import Rectangle


class test_rectangle(unittest.TestCase):
    """test rectangle class"""
    def test_init(self):
        """init no arg"""
        obj = Rectangle(2, 4)
        self.assertEqual(obj.width, 2)
        self.assertEqual(obj.height, 4)

    def test_width_getter(self):
        """test width getter"""
        obj = Rectangle(3, 5)
        self.assertEqual(obj.width, 3)

    def test_height_getter(self):
        """test height getter"""
        obj = Rectangle(3, 5)
        self.assertEqual(obj.height, 5)

    def test_x_getter(self):
        """test x getter"""
        obj = Rectangle(3, 5)
        self.assertEqual(obj.x, 0)

    def test_y_getter(self):
        """test y getter"""
        obj = Rectangle(3, 5)
        self.assertEqual(obj.y, 0)

    def test_setter(self):
        """test getter"""
        obj = Rectangle(3, 5)
        obj.width = 5
        obj.height = 7
        obj.x = 2
        obj.y = 2
        self.assertEqual(obj.width, 5)
        self.assertEqual(obj.height, 7)
        self.assertEqual(obj.x, 2)
        self.assertEqual(obj.y, 2)

     def test_rectangle_is_base(self):
        self.assertIsInstance(Rectangle(10, 2), Base)

    def test_no_args(self):
        with self.assertRaises(TypeError):
            Rectangle()

    def test_one_arg(self):
        with self.assertRaises(TypeError):
            Rectangle(1)

    def test_two_args(self):
        r1 = Rectangle(10, 2)
        r2 = Rectangle(2, 10)
        self.assertEqual(r1.id, r2.id - 1)

    def test_three_args(self):
        r1 = Rectangle(2, 2, 4)
        r2 = Rectangle(4, 4, 2)
        self.assertEqual(r1.id, r2.id - 1)

    def test_four_args(self):
        r1 = Rectangle(1, 2, 3, 4)
        r2 = Rectangle(4, 3, 2, 1)
        self.assertEqual(r1.id, r2.id - 1)

    def test_five_args(self):
        self.assertEqual(7, Rectangle(10, 2, 0, 0, 7).id)

     def test_more_than_five_args(self):
        with self.assertRaises(TypeError):
            Rectangle(1, 2, 3, 4, 5, 6)

    def test_width_private(self):
        with self.assertRaises(AttributeError):
            print(Rectangle(5, 5, 0, 0, 1).__width)

    def test_height_private(self):
        with self.assertRaises(AttributeError):
            print(Rectangle(5, 5, 0, 0, 1).__height)

     def test_x_private(self):
        with self.assertRaises(AttributeError):
            print(Rectangle(5, 5, 0, 0, 1).__x)

    def test_y_private(self):
        with self.assertRaises(AttributeError):
            print(Rectangle(5, 5, 0, 0, 1).__y)

    def test_width_getter(self):
        r = Rectangle(5, 7, 7, 5, 1)
        self.assertEqual(5, r.width)

     def test_width_setter(self):
        r = Rectangle(5, 7, 7, 5, 1)
        r.width = 10
        self.assertEqual(10, r.width)

    def test_height_getter(self):
        r = Rectangle(5, 7, 7, 5, 1)
        self.assertEqual(7, r.height)

    def test_height_setter(self):
        r = Rectangle(5, 7, 7, 5, 1)
        r.height = 10
        self.assertEqual(10, r.height)



    def test_area(self):
        """test area"""
        obj = Rectangle(3, 5)
        self.assertEqual(obj.area(), 15)
